[package]
name = "sunflower"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
ctrlc = "3.4.2"
subprocess = "0.2.9"
bytes = "1.5.0"
